//
//  WorkoutSymbolMapper.swift
//  Bloom
//
//  Created by Matthew Jörke on 2/7/25.
//

import Foundation

// swiftlint:disable cyclomatic_complexity function_body_length
func systemSymbol(for workoutType: String) -> String {
    let key = workoutType.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
    
    switch key {
    case "walking": return "figure.walk"
    case "running": return "figure.run"
    case "american football": return "figure.american.football"
    case "archery": return "figure.archery"
    case "australian football": return "figure.australian.football"
    case "badminton": return "figure.badminton"
    case "baseball": return "figure.baseball"
    case "basketball": return "figure.basketball"
    case "bowling": return "figure.bowling"
    case "boxing": return "figure.boxing"
    case "climbing": return "figure.climbing"
    case "cricket": return "figure.cricket"
    case "cross training": return "figure.cross.training"
    case "curling": return "figure.curling"
    case "cycling": return "figure.outdoor.cycle"
    case "dance": return "figure.dance"
    case "dance inspired training": return "figure.socialdance"
    case "elliptical": return "figure.elliptical"
    case "equestrian sports": return "figure.equestrian.sports"
    case "fencing": return "figure.fencing"
    case "fishing": return "figure.fishing"
    case "functional strength training": return "figure.strengthtraining.functional"
    case "golf": return "figure.golf"
    case "gymnastics": return "figure.gymnastics"
    case "handball": return "figure.handball"
    case "hiking": return "figure.hiking"
    case "hockey": return "figure.hockey"
    case "hunting": return "figure.hunting"
    case "lacrosse": return "figure.lacrosse"
    case "martial arts": return "figure.martial.arts"
    case "mind and body": return "figure.mind.and.body"
    case "mixed metabolic cardio training": return "figure.mixed.cardio"
    case "paddle sports": return "figure.rolling"
    case "play": return "figure.play"
    case "preparation and recovery": return "figure.cooldown"
    case "racquetball": return "figure.racquetball"
    case "rowing": return "figure.indoor.rowing"
    case "rugby": return "figure.rugby"
    case "sailing": return "figure.sailing"
    case "skating sports": return "figure.skateboarding"
    case "snow sports": return "figure.skiing.crosscountry"
    case "soccer": return "figure.outdoor.soccer"
    case "softball": return "figure.softball"
    case "squash": return "figure.squash"
    case "stair climbing": return "figure.stairs"
    case "surfing sports": return "figure.surfing"
    case "swimming": return "figure.pool.swim"
    case "table tennis": return "figure.table.tennis"
    case "tennis": return "figure.tennis"
    case "track and field": return "figure.track.and.field"
    case "traditional strength training": return "figure.strengthtraining.traditional"
    case "volleyball": return "figure.volleyball"
    case "water fitness": return "figure.water.fitness"
    case "water polo": return "figure.waterpolo"
    case "water sports": return "figure.surfing"
    case "wrestling": return "figure.wrestling"
    case "yoga": return "figure.yoga"
    case "barre": return "figure.barre"
    case "core training": return "figure.core.training"
    case "cross country skiing": return "figure.skiing.crosscountry"
    case "downhill skiing": return "figure.skiing.downhill"
    case "flexibility": return "figure.flexibility"
    case "high intensity interval training": return "figure.highintensity.intervaltraining"
    case "jump rope": return "figure.jumprope"
    case "kickboxing": return "figure.kickboxing"
    case "pilates": return "figure.pilates"
    case "snowboarding": return "figure.snowboarding"
    case "stairs": return "figure.stairs"
    case "step training": return "figure.step.training"
    case "wheelchair walk pace": return "figure.roll.runningpace"
    case "wheelchair run pace": return "figure.roll.runningpace"
    case "tai chi": return "figure.taichi"
    case "mixed cardio": return "figure.mixed.cardio"
    case "hand cycling": return "figure.hand.cycling"
    case "disc sports": return "figure.disc.sports"
    case "fitness gaming": return "figure.mind.and.body"
    case "cardio dance": return "figure.dance"
    case "social dance": return "figure.socialdance"
    case "pickleball": return "figure.pickleball"
    case "cooldown": return "figure.cooldown"
    case "swim bike run": return "figure.mixed.cardio"
    case "transition": return "figure.cooldown"
    default:
        return "figure.mixed.cardio"
    }
}
